SIANXSVC-1222: Add binary file API
anexia/go-e5e pull request #8
Opened 2024-02-13 15:44 UTC by nachtjasmin

This PR adds a binary API similar to the one in dotnet-e5e.
The example from the current documentation for binary files was taken and adjusted for this new API.

Closes SIANXSVC-1222

2024-02-26 14:33 UTC, beachmachine requested changes

2024-02-26 14:33 UTC, beachmachine commented on file.go
> +	Base64Encoded   string `json:"binary"`
Not sure why, but there is no `binary` field in the response.

2024-02-26 14:33 UTC, beachmachine commented on file.go
> +	Type            string `json:"type"`
Not sure why, but the type is set to `""` in the response.

2024-02-27 08:34 UTC, nachtjasmin commented on file.go
> +	Type            string `json:"type"`
Out of curiosity, how did you test it?

2024-02-28 08:44 UTC, beachmachine approved these changes

2024-02-28 08:44 UTC, merged